///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Test
{
    /// <summary>
    ///The Fight recording.
    /// </summary>
    [TestModule("99ffaff2-731f-4feb-bc46-ec66ab89ecd3", ModuleType.Recording, 1)]
    public partial class Fight : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestRepository repository.
        /// </summary>
        public static TestRepository repo = TestRepository.Instance;

        static Fight instance = new Fight();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Fight()
        {
            doubleWeapon = "true";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Fight Instance
        {
            get { return instance; }
        }

#region Variables

        string _doubleWeapon;

        /// <summary>
        /// Gets or sets the value of variable doubleWeapon.
        /// </summary>
        [TestVariable("903120a8-8477-42b6-89f0-ec4378b59f7c")]
        public string doubleWeapon
        {
            get { return _doubleWeapon; }
            set { _doubleWeapon = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.2.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.2.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            DoFight(ValueConverter.ArgumentFromString<bool>("fightComplete", "False"));
            Delay.Milliseconds(3760);
            
        }

#region Image Feature Data
#endregion
    }
}
