///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace Test
{
    public partial class WaitingFight
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        private void Wait(Ranorex.Duration min, Ranorex.Duration max)
        {
        	Random R=new Random();
        	Thread.Sleep(R.Next(min,max));
        	
        }

        public void Validate_Вперёд()
        {
            Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'БойцовскийКлуб1.Menu.Вперёд'.", repo.БойцовскийКлуб1.Menu.ВперёдInfo);
            if(Validate.Exists(repo.БойцовскийКлуб1.Menu.ВперёдInfo, Validate.DefaultMessage, false))
            	Fight.Start();
        }
        
        

    }
}